Repository thongdanghoang/greenbuildings, pull requests merged in 2025-05, with the labels that each got.

#358 feature: Linked Tenant Component
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/EmissionActivityCriteria.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/decorators/EmissionActivityMapperDecorator.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EmissionActivityRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EmissionActivityServiceImpl.java
  sep490-frontend/src/app/app-routing.constant.ts
  sep490-frontend/src/app/models/emission-activity.ts
  sep490-frontend/src/app/modules/enterprise/components/building-management/building-management.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-management/building-management.component.ts
  sep490-frontend/src/app/modules/enterprise/components/emission-activity-detail/emission-activity-detail.component.ts
  sep490-frontend/src/app/modules/enterprise/components/manage-common-activity/manage-common-activity.component.css
  sep490-frontend/src/app/modules/enterprise/components/manage-common-activity/manage-common-activity.component.html
  sep490-frontend/src/app/modules/enterprise/components/manage-common-activity/manage-common-activity.component.ts
  sep490-frontend/src/app/modules/enterprise/enterprise-routing.module.ts
  sep490-frontend/src/app/modules/enterprise/enterprise.module.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, improvement, task

#361 fix: Move activity type component, refactor logic
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/ActivityTypeCriteriaDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/ActivityTypeMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/ActivityTypeRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/ActivityTypeServiceImpl.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/ActivityTypeControllerTest.java
  sep490-frontend/src/app/components/sidebar/sidebar.component.ts
  sep490-frontend/src/app/models/emission-activity.ts
  sep490-frontend/src/app/modules/enterprise/components/activity-type/activity-type.component.html
  sep490-frontend/src/app/modules/enterprise/components/activity-type/activity-type.component.ts
  sep490-frontend/src/app/modules/enterprise/components/building-management/building-management.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-management/building-management.component.ts
  sep490-frontend/src/app/modules/enterprise/components/linked-tenant/linked-tenant.component.html
  sep490-frontend/src/app/modules/enterprise/components/manage-common-activity/manage-common-activity.component.html
  sep490-frontend/src/app/modules/enterprise/dialog/activity-type-dialog/activity-type-dialog.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/new-activity-dialog/new-activity-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/enterprise-routing.module.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: bug, improvement, task

#362 Dev qc bugs
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/TenantTableView.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/BuildingGroupEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EmissionActivityRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/ActivityTypeController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/TenantController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/ActivityTypeService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/TenantService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/ActivityTypeServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/BuildingGroupServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/TenantServiceImpl.java
  sep490-frontend/src/app/model/activity-type-criteria-dto.ts
  sep490-frontend/src/app/modules/enterprise/components/emission-activity-detail/emission-activity-detail.component.css
  sep490-frontend/src/app/modules/enterprise/components/emission-activity-detail/emission-activity-detail.component.html
  sep490-frontend/src/app/modules/enterprise/components/emission-activity-detail/emission-activity-detail.component.ts
  sep490-frontend/src/app/modules/enterprise/components/enterprise-invitation/enterprise-invitation.component.html
  sep490-frontend/src/app/modules/enterprise/components/manage-tenant/manage-tenant.component.html
  sep490-frontend/src/app/modules/enterprise/dialog/building-subcription-dialog/building-subscription-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/dialog/credit-package-guide-dialog/credit-package-guide-dialog.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/new-activity-record-dialog/new-activity-record-dialog.component.ts
  sep490-frontend/src/app/services/application.service.ts
Labels: bug, improvement, task

#363 bugfix: disable not selectable date ranges when create emission activ…
  sep490-commons-api/src/main/java/greenbuildings/commons/api/views/DateRangeView.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/EmissionActivityMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/models/ActivityRecordDateRange.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EmissionActivityRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/EmissionActivityController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/EmissionActivityService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EmissionActivityRecordServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EmissionActivityServiceImpl.java
  sep490-frontend/src/app/model/date-range-view.ts
  sep490-frontend/src/app/modules/enterprise/components/emission-activity-detail/emission-activity-detail.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/new-activity-record-dialog/new-activity-record-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/dialog/new-activity-record-dialog/new-activity-record-dialog.component.ts
  sep490-frontend/src/app/services/emission-activity.service.ts
  sep490-frontend/src/styles/styles.css
Labels: bug, improvement, task

#364 fix: Move activity type component, refactor logic
  sep490-frontend/src/app/app-routing.constant.ts
  sep490-frontend/src/app/components/home/home.component.html
  sep490-frontend/src/app/components/sidebar/sidebar.component.ts
  sep490-frontend/src/app/modules/admin/admin-routing.module.ts
  sep490-frontend/src/app/modules/admin/admin.module.ts
  sep490-frontend/src/app/modules/admin/components/account-management/account-management.component.css
  sep490-frontend/src/app/modules/admin/components/account-management/account-management.component.html
  sep490-frontend/src/app/modules/admin/components/account-management/account-management.component.ts
  sep490-frontend/src/app/modules/admin/components/emission-source/emission-source.component.html
  sep490-frontend/src/app/modules/admin/components/enterprise-management/enterprise-management.component.css
  sep490-frontend/src/app/modules/admin/components/enterprise-management/enterprise-management.component.html
  sep490-frontend/src/app/modules/admin/components/enterprise-management/enterprise-management.component.ts
  sep490-frontend/src/app/modules/admin/components/tenant-management/tenant-management.component.css
  sep490-frontend/src/app/modules/admin/components/tenant-management/tenant-management.component.html
  sep490-frontend/src/app/modules/admin/components/tenant-management/tenant-management.component.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
  sep490-idp/src/main/java/greenbuildings/idp/repository/UserRepository.java
  sep490-idp/src/main/java/greenbuildings/idp/rest/EnterpriseUserRestController.java
  sep490-idp/src/main/java/greenbuildings/idp/service/impl/UserServiceImpl.java
Labels: user story, improvement, task

#365 feature: manage enterprise
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/EnterpriseSearchCriteria.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/EnterpriseMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EnterpriseRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/EnterpriseController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/EnterpriseService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EnterpriseServiceImpl.java
  sep490-frontend/src/app/model/enterprise-search-criteria.ts
  sep490-frontend/src/app/model/search-criteria-dto-enterprise-search-criteria.ts
  sep490-frontend/src/app/model/search-result-dto-enterprise-dto.ts
  sep490-frontend/src/app/modules/admin/components/enterprise-management/enterprise-management.component.html
  sep490-frontend/src/app/modules/admin/components/enterprise-management/enterprise-management.component.ts
  sep490-frontend/src/app/services/enterprise.service.ts
Labels: user story, task

#366 feature: manage tenant
  sep490-commons-springfw-impl/src/main/java/commons/springfw/impl/utils/SecurityUtils.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/TenantTableView.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/TenantRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/TenantController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/TenantService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/TenantServiceImpl.java
  sep490-frontend/src/app/modules/admin/components/account-management/account-management.component.html
  sep490-frontend/src/app/modules/admin/components/enterprise-management/enterprise-management.component.html
  sep490-frontend/src/app/modules/admin/components/tenant-management/tenant-management.component.html
  sep490-frontend/src/app/modules/admin/components/tenant-management/tenant-management.component.ts
  sep490-frontend/src/app/services/tenant.service.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, improvement, task

#368 feature: tenant detail for enterprise owner
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/TenantDetailDTO.java
  sep490-frontend/src/app/model/tenant-detail-dto.ts
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.ts
  sep490-frontend/src/app/modules/enterprise/components/linked-tenant/linked-tenant.component.html
  sep490-frontend/src/app/modules/enterprise/components/linked-tenant/linked-tenant.component.ts
  sep490-frontend/src/app/modules/enterprise/components/tenant-profile/tenant-profile.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/tenant-detail-dialog/tenant-detail-dialog.component.css
  sep490-frontend/src/app/modules/enterprise/dialog/tenant-detail-dialog/tenant-detail-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/dialog/tenant-detail-dialog/tenant-detail-dialog.component.ts
  sep490-frontend/src/app/modules/enterprise/enterprise.module.ts
  sep490-frontend/src/app/services/tenant.service.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, improvement, task

#372 Feature/admin management component
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/BuildingGroupController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/BuildingGroupService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/BuildingGroupServiceImpl.java
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.ts
  sep490-frontend/src/app/modules/enterprise/components/new-tenant/new-tenant.component.ts
  sep490-frontend/src/app/services/building-group.service.ts
Labels: user story, improvement, task

#373 Feature/admin management component
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/BuildingGroupController.java
  sep490-frontend/src/app/modules/enterprise/dialog/enteprise-detail-dialog/enterprise-detail-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/dialog/enteprise-detail-dialog/enterprise-detail-dialog.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/tenant-detail-dialog/tenant-detail-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/dialog/tenant-detail-dialog/tenant-detail-dialog.component.ts
  sep490-frontend/src/app/services/storage.service.ts
Labels: user story, improvement, task

#374 feat/add import excel emission
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/ExcelImportDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/ExcelImportFileEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/enums/ImportExcelType.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/ExcelImportMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/ExcelImportFileRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/EmissionFactorController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/EmissionSourceController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/EnergyConversionController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/EmissionFactorService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/EmissionSourceService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/EnergyConversionService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EmissionFactorServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EmissionSourceServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EnergyConversionServiceImpl.java
  sep490-enterprise/src/main/resources/db/migration/V0.0.1.48__AddTableToStorageExcelImportEmission.sql
  sep490-frontend/src/app/models/enterprise.ts
  sep490-frontend/src/app/modules/admin/components/emission-factor/emission-factor.component.html
  sep490-frontend/src/app/modules/admin/components/emission-factor/emission-factor.component.ts
  sep490-frontend/src/app/modules/admin/components/emission-source/emission-source.component.html
  sep490-frontend/src/app/modules/admin/components/emission-source/emission-source.component.ts
  sep490-frontend/src/app/modules/admin/components/fuel-conversion/fuel-conversion.component.html
  sep490-frontend/src/app/modules/admin/components/fuel-conversion/fuel-conversion.component.ts
  sep490-frontend/src/app/services/emission-source.service.ts
  sep490-frontend/src/app/services/emission_factor.service.ts
  sep490-frontend/src/app/services/fuel-conversion.service.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: improvement, task

#386 Fix/bugfix 4 may
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/PaymentMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/ActivityTypeRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/ActivityTypeServiceImpl.java
  sep490-frontend/src/app/modules/enterprise/components/payment/payment.component.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
  sep490-idp/src/main/java/greenbuildings/idp/dto/RegisterEnterpriseDTO.java
Labels: bug

#392 feature: export report
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/DownloadReportDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EmissionActivityRecordRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EmissionActivityRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/BuildingServiceImpl.java
  sep490-enterprise/src/main/resources/files/Template_Report.xlsx
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/BuildingControllerTest.java
  sep490-frontend/src/app/models/enterprise.ts
  sep490-frontend/src/app/modules/enterprise/components/building-management/building-management.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-management/building-management.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/new-activity-record-dialog/new-activity-record-dialog.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/report-dialog/report-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/dialog/report-dialog/report-dialog.component.ts
  sep490-frontend/src/app/services/building-group.service.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, improvement, task

#387 feat/improve import excel
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EmissionFactorRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EmissionSourceRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EnergyConversionRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/FuelRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EmissionFactorServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EmissionSourceServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EnergyConversionServiceImpl.java
  sep490-frontend/src/app/modules/admin/components/emission-factor/emission-factor.component.html
  sep490-frontend/src/app/modules/admin/components/emission-source/emission-source.component.html
  sep490-frontend/src/app/modules/admin/components/fuel-conversion/fuel-conversion.component.html
Labels: improvement, task

#393 Refactor: Move mail utils upto commons
  sep490-commons-springfw-impl/build.gradle
  sep490-commons-springfw-impl/src/main/java/commons/springfw/impl/config/MailConfig.java
  sep490-commons-springfw-impl/src/main/java/commons/springfw/impl/utils/EmailUtil.java
  sep490-commons-springfw-impl/src/main/java/commons/springfw/impl/utils/IEmailUtil.java
  sep490-commons-springfw-impl/src/main/java/commons/springfw/impl/utils/SEPMailMessage.java
  sep490-enterprise/src/main/resources/application-prod.yml
  sep490-enterprise/src/main/resources/application.yml
  sep490-idp/src/main/java/greenbuildings/idp/controller/ForgotPasswordController.java
  sep490-idp/src/main/java/greenbuildings/idp/service/impl/ForgotPasswordServiceImpl.java
  sep490-idp/src/main/java/greenbuildings/idp/service/impl/UserServiceImpl.java
Labels: technical debt

#394 feature: Passkey redirect
  sep490-frontend/src/app/app-routing.module.ts
  sep490-frontend/src/app/components/home/home.component.ts
  sep490-frontend/src/app/modules/authorization/components/user-profile/user-profile.component.html
  sep490-frontend/src/app/modules/authorization/components/user-profile/user-profile.component.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
  sep490-frontend/src/environments/environment.development.ts
  sep490-frontend/src/environments/environment.ts
  sep490-idp/src/main/resources/i18n/messages.properties
  sep490-idp/src/main/resources/i18n/messages_vi.properties
  sep490-idp/src/main/resources/i18n/messages_zh.properties
  sep490-idp/src/main/resources/templates/account-page.html
  sep490-idp/src/main/resources/templates/login.html
Labels: user story, improvement, task

#396 feature: send mail when unlink tenant
  sep490-commons-springfw-impl/src/main/java/commons/springfw/impl/config/CommonI18nConfig.java
  sep490-commons-springfw-impl/src/main/java/commons/springfw/impl/utils/IMessageUtil.java
  sep490-commons-springfw-impl/src/main/java/commons/springfw/impl/utils/MessageUtil.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/BuildingGroupServiceImpl.java
  sep490-enterprise/src/main/resources/i18n/messages.properties
  sep490-enterprise/src/main/resources/i18n/messages_vi.properties
  sep490-enterprise/src/main/resources/i18n/messages_zh.properties
  sep490-enterprise/src/main/resources/mailTemplates/unlink-tenant_en.ftl
  sep490-enterprise/src/main/resources/mailTemplates/unlink-tenant_vi.ftl
  sep490-enterprise/src/main/resources/mailTemplates/unlink-tenant_zh.ftl
  sep490-idp/src/main/java/greenbuildings/idp/configs/I18nConfig.java
  sep490-idp/src/main/java/greenbuildings/idp/controller/ForgotPasswordController.java
  sep490-idp/src/main/java/greenbuildings/idp/controller/FormLoginController.java
  sep490-idp/src/main/java/greenbuildings/idp/service/impl/ForgotPasswordServiceImpl.java
  sep490-idp/src/main/java/greenbuildings/idp/service/impl/UserServiceImpl.java
Labels: improvement

#400 feature: Add factor name in table
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/EmissionActivityTableView.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/EmissionActivityMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EmissionActivityRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/EmissionActivityController.java
  sep490-frontend/src/app/models/enterprise.ts
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.ts
  sep490-frontend/src/app/modules/enterprise/components/emission-activity/emission-activity.component.ts
  sep490-frontend/src/app/modules/enterprise/components/manage-common-activity/manage-common-activity.component.html
  sep490-frontend/src/app/modules/enterprise/components/manage-common-activity/manage-common-activity.component.ts
  sep490-frontend/src/app/services/emission-activity.service.ts
Labels: user story, improvement, task

#401 feat/fix title description for component at admin
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: improvement

#402 feat/add subtitle for component
  sep490-frontend/src/app/components/dashboard/dashboard.component.html
  sep490-frontend/src/app/modules/admin/components/emission-factor/emission-factor.component.html
  sep490-frontend/src/app/modules/admin/components/fuel-conversion/fuel-conversion.component.html
  sep490-frontend/src/app/modules/authorization/components/power-bi-access-token/power-bi-access-token.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-management/building-management.component.html
  sep490-frontend/src/app/modules/enterprise/components/buildings/buildings.component.html
  sep490-frontend/src/app/modules/enterprise/components/new-building-group/new-building-group.component.html
  sep490-frontend/src/app/modules/enterprise/components/new-tenant/new-tenant.component.html
  sep490-frontend/src/app/modules/enterprise/components/plan/plan.component.html
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
  sep490-frontend/src/assets/images/payment-method/master-card.svg
  sep490-frontend/src/assets/images/payment-method/momo.svg
  sep490-frontend/src/assets/images/payment-method/napas.svg
  sep490-frontend/src/assets/images/payment-method/payos-icon.svg
  sep490-frontend/src/assets/images/payment-method/payos.svg
  sep490-frontend/src/assets/images/payment-method/visa.svg
  sep490-frontend/src/assets/images/payment-method/vnpay.svg
Labels: improvement

#403 feat/send mail invite
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/TenantRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/BuildingGroupController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/BuildingGroupServiceImpl.java
  sep490-enterprise/src/main/resources/i18n/messages.properties
  sep490-enterprise/src/main/resources/i18n/messages_vi.properties
  sep490-enterprise/src/main/resources/i18n/messages_zh.properties
  sep490-enterprise/src/main/resources/mailTemplates/invite-tenant_en.ftl
  sep490-enterprise/src/main/resources/mailTemplates/invite-tenant_vi.ftl
  sep490-enterprise/src/main/resources/mailTemplates/invite-tenant_zh.ftl
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/BuildingGroupControllerTest.java
Labels: user story, improvement, task

#406 feature: general report for powerbi
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/GeneralReportDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/BuildingEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/CalculationService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/CalculationServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/ReportServiceImpl.java
Labels: user story, improvement, task

#409 feat/add field for building
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/BuildingDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/BuildingEntity.java
  sep490-enterprise/src/main/resources/db/migration/V0.0.1.49__AddFieldForBuildingEntity.sql
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/BuildingControllerTest.java
  sep490-frontend/src/app/models/enterprise.ts
  sep490-frontend/src/app/modules/enterprise/components/building-details/building-details.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-details/building-details.component.ts
  sep490-frontend/src/app/modules/enterprise/components/buildings/buildings.component.html
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, improvement, task

#411 Feature/export report
  sep490-enterprise/src/main/resources/power-bi-response.json
  sep490-frontend/src/app/modules/authorization/components/power-bi-access-token/power-bi-access-token.component.html
  sep490-frontend/src/app/modules/authorization/components/power-bi-access-token/power-bi-access-token.component.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
  sep490-idp/src/main/resources/application-prod.yml
Labels: user story, task

#421 bugfix: fix PR
  sep490-frontend/src/app/modules/emissions/emissions.component.ts
  sep490-frontend/src/app/modules/enterprise/components/emission-activity-detail/emission-activity-detail.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/new-activity-dialog/new-activity-dialog.component.ts
Labels: bug

#423 feat/add component for admin
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/PaymentAdminCriteria.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/PaymentEnterpriseAdminDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/TransactionAdminCriteria.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/TransactionEnterpriseAdminDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/PaymentMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/TransactionMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/PaymentRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/TransactionRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/PaymentController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/TransactionController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/PaymentService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/TransactionService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/PaymentServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/TransactionServiceImpl.java
  sep490-enterprise/src/main/resources/application.yml
  sep490-frontend/src/app/app-routing.constant.ts
  sep490-frontend/src/app/components/sidebar/sidebar.component.ts
  sep490-frontend/src/app/models/payment.ts
  sep490-frontend/src/app/models/transactions.ts
  sep490-frontend/src/app/modules/admin/admin-routing.module.ts
  sep490-frontend/src/app/modules/admin/admin.module.ts
  sep490-frontend/src/app/modules/admin/components/payment-enterprise-management/payment-enterprise-management.component.css
  sep490-frontend/src/app/modules/admin/components/payment-enterprise-management/payment-enterprise-management.component.html
  sep490-frontend/src/app/modules/admin/components/payment-enterprise-management/payment-enterprise-management.component.ts
  sep490-frontend/src/app/modules/admin/components/transaction-enterprise-management/transaction-enterprise-management.component.css
  sep490-frontend/src/app/modules/admin/components/transaction-enterprise-management/transaction-enterprise-management.component.html
  sep490-frontend/src/app/modules/admin/components/transaction-enterprise-management/transaction-enterprise-management.component.ts
  sep490-frontend/src/app/services/payment.service.ts
  sep490-frontend/src/app/services/transaction.service.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, improvement, task

#427 feature: activity type logic
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/decorators/EmissionActivityMapperDecorator.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/ActivityTypeRepository.java
  sep490-frontend/src/app/modules/enterprise/dialog/new-activity-dialog/new-activity-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/dialog/new-activity-dialog/new-activity-dialog.component.ts
Labels: user story, improvement, task

#428 feat/fix translate language
  sep490-frontend/src/app/modules/authorization/components/power-bi-access-token-detail/power-bi-access-token-detail.component.html
  sep490-frontend/src/app/modules/authorization/components/power-bi-access-token/power-bi-access-token.component.html
  sep490-frontend/src/app/modules/enterprise/components/enterprise-invitation/enterprise-invitation.component.html
  sep490-frontend/src/app/modules/enterprise/components/manage-tenant/manage-tenant.component.html
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: improvement

#431 feat/add user guide power bi
  sep490-frontend/src/app/app-routing.constant.ts
  sep490-frontend/src/app/modules/authorization/authorization-routing.module.ts
  sep490-frontend/src/app/modules/authorization/authorization.module.ts
  sep490-frontend/src/app/modules/authorization/components/power-bi-access-token/power-bi-access-token.component.html
  sep490-frontend/src/app/modules/authorization/components/power-bi-access-token/power-bi-access-token.component.ts
  sep490-frontend/src/app/modules/authorization/components/user-guide-power-bi/user-guide-power-bi.component.css
  sep490-frontend/src/app/modules/authorization/components/user-guide-power-bi/user-guide-power-bi.component.html
  sep490-frontend/src/app/modules/authorization/components/user-guide-power-bi/user-guide-power-bi.component.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
  sep490-frontend/src/assets/images/guide-power-bi/guide1.png
  sep490-frontend/src/assets/images/guide-power-bi/guide10.png
  sep490-frontend/src/assets/images/guide-power-bi/guide11.png
  sep490-frontend/src/assets/images/guide-power-bi/guide2.png
  sep490-frontend/src/assets/images/guide-power-bi/guide3.png
  sep490-frontend/src/assets/images/guide-power-bi/guide4.png
  sep490-frontend/src/assets/images/guide-power-bi/guide5.png
  sep490-frontend/src/assets/images/guide-power-bi/guide6.png
  sep490-frontend/src/assets/images/guide-power-bi/guide7.png
  sep490-frontend/src/assets/images/guide-power-bi/guide8.png
  sep490-frontend/src/assets/images/guide-power-bi/guide9.png
Labels: user story, improvement, task

#436 Fix/bugfix 14 5
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/TenantDetailDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EnergyConversionRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/EnergyConversionController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/EnergyConversionService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EnergyConversionServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/TenantServiceImpl.java
  sep490-frontend/src/app/modules/enterprise/components/new-tenant/new-tenant.component.html
  sep490-frontend/src/app/modules/enterprise/components/new-tenant/new-tenant.component.ts
  sep490-frontend/src/app/modules/enterprise/components/tenant-profile/tenant-profile.component.html
  sep490-frontend/src/app/modules/enterprise/components/tenant-profile/tenant-profile.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/new-activity-record-dialog/new-activity-record-dialog.component.ts
  sep490-frontend/src/app/services/fuel-conversion.service.ts
Labels: bug

#461 Bugfix/duplicate asset when add new activity emissions at fptu hcm building
  sep490-commons-springfw-impl/src/main/java/greenbuildings/commons/springfw/impl/utils/EmailUtil.java
  sep490-enterprise/build.gradle
  sep490-enterprise/src/main/java/greenbuildings/enterprise/configs/WebClientConfig.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/events/BuildingGroupUnlinkedEvent.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/AssetRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/AssetService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/IdpClientService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/AssetServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/BuildingGroupServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/IdpClientServiceImpl.java
  sep490-frontend/src/app/application.constant.ts
  sep490-frontend/src/app/model/enterprise-user-dto.ts
  sep490-frontend/src/app/modules/enterprise/components/assets-view/assets-view.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.ts
Labels: bug

#465 Feature/20 may
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/ReportServiceImpl.java
  sep490-enterprise/src/main/resources/files/Template_Report.xlsx
Labels: improvement, task

#471 feat/fix bug #468
  sep490-frontend/src/app/components/email-verify-otp/email-verify-otp.component.css
  sep490-frontend/src/app/components/email-verify-otp/email-verify-otp.component.html
  sep490-frontend/src/app/components/email-verify-otp/email-verify-otp.component.ts
  sep490-frontend/src/app/modules/enterprise/components/create-enterprise/create-enterprise.component.css
  sep490-frontend/src/app/modules/enterprise/components/create-enterprise/create-enterprise.component.html
  sep490-frontend/src/app/modules/enterprise/components/create-enterprise/create-enterprise.component.ts
Labels: bug, improvement

#473 bugfix/fix bug #470
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EmissionFactorServiceImpl.java
  sep490-frontend/src/app/modules/admin/components/emission-factor/emission-factor.component.html
  sep490-frontend/src/app/modules/admin/components/emission-source/emission-source.component.html
  sep490-frontend/src/app/modules/admin/components/fuel-conversion/fuel-conversion.component.html
Labels: bug

#475 feature: add Power BI data endpoints and update emission activities h…
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/EmissionActivityEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/PowerBiMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EmissionActivityRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/DashboardResource.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/PowerBiResource.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/EmissionActivityService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/ReportService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/AssetServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EmissionActivityServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/ReportServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/views/powerbi/EmissionActivityGhg.java
  sep490-frontend/src/app/modules/authorization/components/power-bi-access-token/power-bi-access-token.component.ts
Labels: improvement, task
