Repository thongdanghoang/greenbuildings, pull requests merged in 2025-04, with the labels that each got.

#221 196-powerbi-integration
  sep490-commons/api/src/main/java/greenbuildings/commons/api/events/PowerBiAccessTokenAuthResult.java
  sep490-commons/api/src/main/java/greenbuildings/commons/api/security/PowerBiScope.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/dashboard/SelectableBuildingDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/BuildingMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/BuildingController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/PowerBiResource.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/securities/IAuthenticationFacade.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/securities/PowerBiAuthentication.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/securities/PowerBiAuthenticationFacade.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/BuildingService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/BuildingServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/validators/PowerBiSecurityCheckerBean.java
  sep490-frontend/src/app/modules/authorization/components/create-user/enterprise-user-details.component.ts
  sep490-frontend/src/app/modules/authorization/components/power-bi-access-token-detail/power-bi-access-token-detail.component.html
  sep490-frontend/src/app/modules/authorization/components/power-bi-access-token-detail/power-bi-access-token-detail.component.ts
  sep490-frontend/src/app/modules/authorization/components/power-bi-access-token-expiration-options.ts
  sep490-frontend/src/app/modules/authorization/components/power-bi-access-token/power-bi-access-token.component.html
  sep490-frontend/src/app/modules/authorization/components/power-bi-access-token/power-bi-access-token.component.ts
  sep490-frontend/src/app/modules/authorization/components/power-bi-regenerate-access-token/power-bi-regenerate-access-token.component.ts
  sep490-frontend/src/app/modules/authorization/models/power-bi-access-token.dto.ts
  sep490-frontend/src/app/modules/authorization/services/power-bi-access-token.service.ts
  sep490-idp/src/main/java/greenbuildings/idp/dto/powerbi/PowerBiAuthorityDTO.java
  sep490-idp/src/main/java/greenbuildings/idp/entity/PowerBiAuthority.java
  sep490-idp/src/main/java/greenbuildings/idp/rest/PowerBiResource.java
  sep490-idp/src/main/java/greenbuildings/idp/service/impl/PowerBiAuthenticationServiceImpl.java
  sep490-idp/src/main/resources/db/migration/V0.0.1.13__PowerBiScope.sql
  sep490-idp/src/main/resources/db/migration/V0.0.1.14__PowerBiBelongToEnterpriseInstead.sql
Labels: task

#224 Feature/calculation
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/DownloadReportDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EmissionActivityRecordRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EmissionActivityRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/BuildingController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/EmissionActivityController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/BuildingService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/EmissionActivityService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/BuildingServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EmissionActivityServiceImpl.java
  sep490-frontend/src/app/modules/enterprise/components/emission-activity/emission-activity.component.html
  sep490-frontend/src/app/modules/enterprise/components/emission-activity/emission-activity.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/report-dialog/report-dialog.component.css
  sep490-frontend/src/app/modules/enterprise/dialog/report-dialog/report-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/dialog/report-dialog/report-dialog.component.ts
  sep490-frontend/src/app/modules/enterprise/enterprise.module.ts
  sep490-frontend/src/app/modules/enterprise/models/enterprise.dto.ts
  sep490-frontend/src/app/modules/enterprise/services/emission-activity.service.ts
  sep490-frontend/src/app/services/building.service.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, task

#231 feature: Move type from building to enterprise
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/ActivityTypeDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/ActivityTypeEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/BuildingEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/EnterpriseEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/ActivityTypeMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/decorators/EmissionActivityMapperDecorator.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/ActivityTypeRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/ActivityTypeController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/ActivityTypeService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/ActivityTypeServiceImpl.java
  sep490-enterprise/src/main/resources/db/migration/V0.0.1.33__MoveActivityTypeToEnterprise.sql
  sep490-frontend/src/app/modules/enterprise/components/emission-activity-detail/emission-activity-detail.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/new-activity-dialog/new-activity-dialog.component.ts
  sep490-frontend/src/app/modules/enterprise/models/enterprise.dto.ts
  sep490-frontend/src/app/modules/enterprise/services/activity-type.service.ts
Labels: user story, task

#232 feature: Improve factor admin
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/EmissionFactorDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/EmissionActivityMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EmissionFactorServiceImpl.java
  sep490-frontend/src/app/modules/admin/components/emission-factor/emission-factor.component.html
  sep490-frontend/src/app/modules/admin/components/emission-factor/emission-factor.component.ts
  sep490-frontend/src/app/modules/admin/dialog/emission-factor-dialog/emission-factor-dialog.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/new-activity-record-dialog/new-activity-record-dialog.component.ts
  sep490-frontend/src/app/modules/shared/models/shared-models.ts
Labels: user story, improvement, task

#233 Feat/fix workflow create building and add api goong map
  sep490-commons/api/src/main/java/greenbuildings/commons/api/exceptions/BusinessException.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/ActivityTypeCriteriaDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/enums/GwpConfiguration.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/ActivityTypeMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/ActivityTypeRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EmissionActivityRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/ActivityTypeController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/ActivityTypeService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/ActivityTypeServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EmissionFactorServiceImpl.java
  sep490-frontend/src/app/app-routing.constant.ts
  sep490-frontend/src/app/components/sidebar/sidebar.component.ts
  sep490-frontend/src/app/modules/enterprise/components/activity-type/activity-type.component.css
  sep490-frontend/src/app/modules/enterprise/components/activity-type/activity-type.component.html
  sep490-frontend/src/app/modules/enterprise/components/activity-type/activity-type.component.ts
  sep490-frontend/src/app/modules/enterprise/components/building-details/building-details.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-details/building-details.component.ts
  sep490-frontend/src/app/modules/enterprise/components/buildings/buildings.component.html
  sep490-frontend/src/app/modules/enterprise/components/buildings/buildings.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/activity-type-dialog/activity-type-dialog.component.css
  sep490-frontend/src/app/modules/enterprise/dialog/activity-type-dialog/activity-type-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/dialog/activity-type-dialog/activity-type-dialog.component.ts
  sep490-frontend/src/app/modules/enterprise/enterprise-routing.module.ts
  sep490-frontend/src/app/modules/enterprise/enterprise.module.ts
  sep490-frontend/src/app/modules/enterprise/services/activity-type.service.ts
  sep490-frontend/src/app/modules/shared/shared.module.ts
  sep490-frontend/src/app/services/geocoding.service.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, improvement, task

#236 feature: Export report in xlsx
  sep490-enterprise/build.gradle
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EmissionActivityRecordRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/BuildingController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/BuildingService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/BuildingServiceImpl.java
  sep490-enterprise/src/main/resources/files/Template_Report.xlsx
  sep490-frontend/src/app/modules/enterprise/dialog/report-dialog/report-dialog.component.ts
Labels: user story, improvement, task

#240 feat/manage-chemical-density-admin
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/ChemicalDensityCriteria.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/ChemicalDensityDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/ChemicalDensityMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/ChemicalDensityRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/ChemicalDensityController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/ChemicalDensityService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/ChemicalDensityServiceImpl.java
  sep490-frontend/src/app/app-routing.constant.ts
  sep490-frontend/src/app/components/sidebar/sidebar.component.ts
  sep490-frontend/src/app/modules/admin/admin-routing.module.ts
  sep490-frontend/src/app/modules/admin/admin.module.ts
  sep490-frontend/src/app/modules/admin/components/chemical-density/chemical-density.component.css
  sep490-frontend/src/app/modules/admin/components/chemical-density/chemical-density.component.html
  sep490-frontend/src/app/modules/admin/components/chemical-density/chemical-density.component.ts
  sep490-frontend/src/app/modules/admin/dialog/chemical-density-dialog/chemical-density-dialog.component.css
  sep490-frontend/src/app/modules/admin/dialog/chemical-density-dialog/chemical-density-dialog.component.html
  sep490-frontend/src/app/modules/admin/dialog/chemical-density-dialog/chemical-density-dialog.component.ts
  sep490-frontend/src/app/modules/admin/services/chemical-density.service.ts
  sep490-frontend/src/app/modules/shared/models/shared-models.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, improvement, task

#263 bugfix: Responsive issues on mobile
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/BuildingController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/EmissionFactorController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/EmissionFactorService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EmissionFactorServiceImpl.java
  sep490-frontend/src/app/app.component.html
  sep490-frontend/src/app/components/header/header.component.html
  sep490-frontend/src/app/components/header/header.component.ts
  sep490-frontend/src/app/components/sidebar/sidebar.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-details/building-details.component.html
  sep490-frontend/src/app/modules/enterprise/components/buildings/buildings.component.html
  sep490-frontend/src/app/modules/enterprise/components/emission-activity-detail/emission-activity-detail.component.html
  sep490-frontend/src/app/modules/enterprise/components/emission-activity/emission-activity.component.html
  sep490-frontend/src/app/services/building.service.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: improvement, task

#270 feat/detail transaction payment and transacton credit history at buil…
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/PaymentDetailDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/TransactionDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/PaymentMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/TransactionMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/PaymentRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/TransactionRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/PaymentController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/TransactionController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/PaymentService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/TransactionService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/PaymentServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/SubscriptionServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/TransactionServiceImpl.java
  sep490-frontend/src/app/modules/enterprise/components/buildings/buildings.component.html
  sep490-frontend/src/app/modules/enterprise/components/buildings/buildings.component.ts
  sep490-frontend/src/app/modules/enterprise/components/payment/payment.component.html
  sep490-frontend/src/app/modules/enterprise/components/payment/payment.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/credit-deduction-history-dialog/credit-deduction-history-dialog.component.css
  sep490-frontend/src/app/modules/enterprise/dialog/credit-deduction-history-dialog/credit-deduction-history-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/dialog/credit-deduction-history-dialog/credit-deduction-history-dialog.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/payment-detail-dialog/payment-detail-dialog.component.css
  sep490-frontend/src/app/modules/enterprise/dialog/payment-detail-dialog/payment-detail-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/dialog/payment-detail-dialog/payment-detail-dialog.component.ts
  sep490-frontend/src/app/modules/enterprise/enterprise.module.ts
  sep490-frontend/src/app/modules/enterprise/models/enterprise.dto.ts
  sep490-frontend/src/app/modules/enterprise/models/payment.ts
  sep490-frontend/src/app/modules/enterprise/services/payment.service.ts
  sep490-frontend/src/app/modules/enterprise/services/transaction.service.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, improvement, task

#271 feat/add field description in activity type
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/ActivityTypeDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/ActivityTypeEntity.java
  sep490-enterprise/src/main/resources/db/migration/V0.0.1.36__AddFieldDescriptionInActivityType.sql
  sep490-frontend/src/app/modules/enterprise/components/activity-type/activity-type.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/activity-type-dialog/activity-type-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/dialog/activity-type-dialog/activity-type-dialog.component.ts
  sep490-frontend/src/app/modules/enterprise/models/enterprise.dto.ts
Labels: user story, improvement, task

#282 bugfix
  sep490-frontend/src/app/modules/authorization/components/power-bi-access-token-detail/power-bi-access-token-detail.component.html
  sep490-frontend/src/app/modules/authorization/components/power-bi-access-token/power-bi-access-token.component.html
  sep490-frontend/src/app/modules/authorization/components/power-bi-access-token/power-bi-access-token.component.ts
  sep490-frontend/src/app/services/building.service.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
  sep490-idp/src/main/java/greenbuildings/idp/entity/PowerBiAuthority.java
  sep490-idp/src/main/java/greenbuildings/idp/rest/PowerBiResource.java
  sep490-idp/src/main/java/greenbuildings/idp/service/impl/PowerBiAuthenticationServiceImpl.java
  sep490-idp/src/main/resources/db/migration/V0.0.1.15__PowerBiLastUsed.sql
Labels: task

#284 276 angular timezone issue
  sep490-frontend/src/app/modules/enterprise/dialog/new-activity-record-dialog/new-activity-record-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/dialog/new-activity-record-dialog/new-activity-record-dialog.component.ts
  sep490-frontend/src/app/modules/shared/components/table-template/table-template.component.html
Labels: improvement, task

#286 bugfix: manually convert js Date to UTC before submit
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/CreditPackageDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/CreditPackageVersionEntity.java
  sep490-enterprise/src/main/resources/db/migration/V0.0.1.38__CreditPackageVersionDiscount.sql
  sep490-frontend/src/app/modules/admin/components/create-update-package-credit/create-update-package-credit.component.html
  sep490-frontend/src/app/modules/admin/components/create-update-package-credit/create-update-package-credit.component.ts
  sep490-frontend/src/app/modules/dev/components/toolbox/toolbox.component.html
  sep490-frontend/src/app/modules/enterprise/components/plan/plan.component.css
  sep490-frontend/src/app/modules/enterprise/components/plan/plan.component.html
  sep490-frontend/src/app/modules/enterprise/components/plan/plan.component.ts
  sep490-frontend/src/app/modules/enterprise/models/enterprise.dto.ts
  sep490-frontend/src/app/modules/shared/components/card/card-template/card-template.component.css
  sep490-frontend/src/app/modules/shared/components/card/card-template/card-template.component.html
  sep490-frontend/src/app/modules/shared/components/card/card-template/card-template.component.ts
  sep490-frontend/src/app/modules/shared/shared.module.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: improvement, task

#290 feat/subscription-popup and fix mixed
  sep490-frontend/src/app/components/header/header.component.ts
  sep490-frontend/src/app/components/sidebar/sidebar.component.ts
  sep490-frontend/src/app/modules/admin/components/create-update-package-credit/create-update-package-credit.component.html
  sep490-frontend/src/app/modules/admin/components/create-update-package-credit/create-update-package-credit.component.ts
  sep490-frontend/src/app/modules/authorization/components/user-profile/user-profile.component.html
  sep490-frontend/src/app/modules/authorization/components/user-profile/user-profile.component.ts
  sep490-frontend/src/app/modules/enterprise/components/plan/plan.component.html
  sep490-frontend/src/app/modules/enterprise/components/plan/plan.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/credit-package-guide-dialog/credit-package-guide-dialog.component.css
  sep490-frontend/src/app/modules/enterprise/dialog/credit-package-guide-dialog/credit-package-guide-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/dialog/credit-package-guide-dialog/credit-package-guide-dialog.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/payment-detail-dialog/payment-detail-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/enterprise.module.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, improvement, task

#295 183: more UT, IT
  sep490-commons/springfw-impl/src/main/java/commons/springfw/impl/mappers/GreenBuildingsMapper.java
  sep490-enterprise/build.gradle
  sep490-enterprise/lombok.config
  sep490-enterprise/src/main/java/greenbuildings/enterprise/configs/MinioConfig.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/ActivityTypeDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/CreditPackageDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/EmissionFactorDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/EmissionSourceDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/EnterpriseDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/CreditPackageVersionRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/ActivityTypeController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/ActivityTypeServiceImpl.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/TestcontainersConfigs.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/adapters/exchangerate_api/ExchangeRateApiCurrencyConverterTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/ActivityTypeControllerTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/BuildingControllerTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/CreditPackageControllerTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/EmissionFactorControllerTest.java
Labels: user story, task

#299 296: more UT, IT
  sep490-commons/api/src/main/java/greenbuildings/commons/api/events/PendingEnterpriseRegisterEvent.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/BuildingGroupCriteria.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/CreateBuildingGroupDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/InviteTenantToBuildingGroup.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/BuildingGroupEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/TenantEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/BuildingGroupRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/TenantRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/BuildingGroupController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/ActivityTypeServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/TenantServiceImpl.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/TestcontainersConfigs.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/adapters/exchangerate_api/ExchangeRateApiCurrencyConverterTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/ActivityTypeControllerTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/BuildingControllerTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/BuildingGroupControllerTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/CreditPackageControllerTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/DevControllerTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/EmissionFactorControllerTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/TenantControllerTest.java
Labels: technical debt, task

#300 Feature/adapt new business flow
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/InvitationResponseDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/InvitationController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/InvitationService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/InvitationServiceImpl.java
  sep490-frontend/src/app/app-routing.constant.ts
  sep490-frontend/src/app/components/sidebar/sidebar.component.ts
  sep490-frontend/src/app/modules/enterprise/components/enterprise-invitation/enterprise-invitation.component.ts
  sep490-frontend/src/app/modules/enterprise/components/manage-tenant/manage-tenant.component.css
  sep490-frontend/src/app/modules/enterprise/components/manage-tenant/manage-tenant.component.html
  sep490-frontend/src/app/modules/enterprise/components/manage-tenant/manage-tenant.component.ts
  sep490-frontend/src/app/modules/enterprise/enterprise-routing.module.ts
  sep490-frontend/src/app/modules/enterprise/enterprise.module.ts
  sep490-frontend/src/app/modules/enterprise/services/invitation.service.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, improvement, task

#302 feature: manage tenant
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/BuildingGroupMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/decorators/BuildingGroupMapperDecorator.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/BuildingGroupController.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/BuildingGroupControllerTest.java
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.ts
  sep490-frontend/src/app/modules/enterprise/components/manage-tenant/manage-tenant.component.html
  sep490-frontend/src/app/modules/enterprise/components/manage-tenant/manage-tenant.component.ts
  sep490-frontend/src/app/modules/enterprise/services/building-group.service.ts
Labels: user story, improvement, task

#308 Test/296 enterprise module
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/DownloadReportDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/SubscribeRequestDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/EmissionActivityEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/EmissionActivityRecordEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EmissionActivityRecordRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/SubscriptionController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/BuildingServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/CalculationServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/ChemicalDensityServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EmissionActivityRecordServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/SubscriptionServiceImpl.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/TestcontainersConfigs.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/BuildingControllerTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/CreditPackageControllerTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/SubscriptionControllerTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/services/CalculationServiceTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/services/EmissionActivityRecordServiceTest.java
Labels: technical debt

#307 feature: create enterprise welcoming
  sep490-frontend/src/app/modules/enterprise/components/create-enterprise/create-enterprise.component.html
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story

#310 feature: Tenant could be assigned to only one group/building.
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/InviteTenantToBuildingGroup.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/BuildingGroupServiceImpl.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/BuildingGroupControllerTest.java
  sep490-frontend/src/app/components/sidebar/sidebar.component.ts
  sep490-frontend/src/app/modules/enterprise/components/new-tenant/new-tenant.component.html
  sep490-frontend/src/app/modules/enterprise/components/new-tenant/new-tenant.component.ts
  sep490-frontend/src/app/modules/enterprise/services/building-group.service.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, improvement, task

#311 feature: Manage sent invitations
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/InvitationSearchCriteria.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/InvitationSearchResult.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/InvitationRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/InvitationController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/InvitationService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/InvitationServiceImpl.java
  sep490-frontend/src/app/app-routing.constant.ts
  sep490-frontend/src/app/components/sidebar/sidebar.component.ts
  sep490-frontend/src/app/modules/enterprise/components/new-tenant/new-tenant.component.html
  sep490-frontend/src/app/modules/enterprise/components/sent-invitation/sent-invitation.component.css
  sep490-frontend/src/app/modules/enterprise/components/sent-invitation/sent-invitation.component.html
  sep490-frontend/src/app/modules/enterprise/components/sent-invitation/sent-invitation.component.ts
  sep490-frontend/src/app/modules/enterprise/enterprise-routing.module.ts
  sep490-frontend/src/app/modules/enterprise/enterprise.module.ts
  sep490-frontend/src/app/modules/enterprise/services/invitation.service.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, improvement, task

#312 feat/help core flow
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/ActivityTypeCriteriaDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/OverviewBuildingDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/ActivityTypeMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/BuildingController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/EmissionSourceController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/BuildingService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/EmissionSourceService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/ActivityTypeServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/BuildingServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EmissionSourceServiceImpl.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/ActivityTypeControllerTest.java
  sep490-frontend/src/app/components/dashboard/dashboard.component.html
  sep490-frontend/src/app/components/sidebar/sidebar.component.ts
  sep490-frontend/src/app/modules/admin/components/emission-source/emission-source.component.css
  sep490-frontend/src/app/modules/admin/components/emission-source/emission-source.component.html
  sep490-frontend/src/app/modules/admin/components/emission-source/emission-source.component.ts
  sep490-frontend/src/app/modules/admin/services/emission-source.service.ts
  sep490-frontend/src/app/modules/enterprise/components/activity-type/activity-type.component.html
  sep490-frontend/src/app/modules/enterprise/components/activity-type/activity-type.component.ts
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.ts
  sep490-frontend/src/app/modules/enterprise/components/building-management/building-management.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-management/building-management.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/activity-type-dialog/activity-type-dialog.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/credit-package-guide-dialog/credit-package-guide-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/dialog/payment-detail-dialog/payment-detail-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/enterprise-routing.module.ts
  sep490-frontend/src/app/modules/enterprise/enterprise.module.ts
  sep490-frontend/src/app/modules/enterprise/models/enterprise.dto.ts
  sep490-frontend/src/app/modules/enterprise/services/activity-type.service.ts
  sep490-frontend/src/app/services/building.service.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
  sep490-frontend/src/assets/images/icon/tenant.png
Labels: user story, improvement, task

#313 feature: restyling cards
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-management/building-management.component.html
Labels: improvement

#315 feat/restyle payment detail
  sep490-frontend/src/app/modules/enterprise/dialog/payment-detail-dialog/payment-detail-dialog.component.html
Labels: improvement

#316 feat/add term and about credit package content
  sep490-frontend/src/app/modules/enterprise/components/plan/plan.component.html
  sep490-frontend/src/app/modules/enterprise/components/plan/plan.component.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, improvement

#317 feat/unique name activity type when create or update
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/ActivityTypeRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/ActivityTypeServiceImpl.java
  sep490-frontend/src/app/components/sidebar/sidebar.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/activity-type-dialog/activity-type-dialog.component.html
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: improvement, task

#318 feature: Email verify OTP
  sep490-frontend/src/app/app.component.html
  sep490-frontend/src/app/app.component.ts
  sep490-frontend/src/app/app.module.ts
  sep490-frontend/src/app/components/email-verify-otp/email-verify-otp.component.css
  sep490-frontend/src/app/components/email-verify-otp/email-verify-otp.component.html
  sep490-frontend/src/app/components/email-verify-otp/email-verify-otp.component.ts
  sep490-frontend/src/app/components/home/home.component.html
  sep490-frontend/src/app/components/home/home.component.ts
  sep490-frontend/src/app/components/sidebar/sidebar.component.ts
  sep490-frontend/src/app/modules/authorization/services/enterprise-user.service.ts
  sep490-frontend/src/app/modules/core/services/application.service.ts
  sep490-frontend/src/app/modules/shared/shared.module.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
  sep490-idp/src/main/java/greenbuildings/idp/dto/ValidateOTPRequest.java
  sep490-idp/src/main/java/greenbuildings/idp/entity/UserEntity.java
  sep490-idp/src/main/java/greenbuildings/idp/entity/UserOTP.java
  sep490-idp/src/main/java/greenbuildings/idp/rest/EnterpriseUserRestController.java
  sep490-idp/src/main/java/greenbuildings/idp/service/UserService.java
  sep490-idp/src/main/java/greenbuildings/idp/service/impl/UserServiceImpl.java
  sep490-idp/src/main/resources/i18n/messages.properties
  sep490-idp/src/main/resources/i18n/messages_vi.properties
  sep490-idp/src/main/resources/i18n/messages_zh.properties
  sep490-idp/src/main/resources/mailTemplates/mail-verify-otp_en.ftl
  sep490-idp/src/main/resources/mailTemplates/mail-verify-otp_vi.ftl
  sep490-idp/src/main/resources/mailTemplates/mail-verify-otp_zh.ftl
Labels: user story, task

#319 feature: Email verify OTP update
  sep490-frontend/src/app/components/email-verify-otp/email-verify-otp.component.html
  sep490-idp/src/main/java/greenbuildings/idp/dto/ValidateOTPRequest.java
  sep490-idp/src/main/resources/mailTemplates/mail-verify-otp_en.ftl
  sep490-idp/src/main/resources/mailTemplates/mail-verify-otp_vi.ftl
  sep490-idp/src/main/resources/mailTemplates/mail-verify-otp_zh.ftl
Labels: improvement

#320 feature: Add logic to display button
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.ts
Labels: user story, improvement, task

#322 Test/296 enterprise module
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/ChemicalDensityDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/EnergyConversionDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/FuelDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/ChemicalDensityEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/PaymentEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/decorators/EnergyConversionMapperDecorator.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/ChemicalDensityRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EnergyConversionRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/PaymentController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/PaymentService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/ChemicalDensityServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/PaymentServiceImpl.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/TestcontainersConfigs.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/ChemicalDensityControllerTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/EmissionSourceControllerTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/EnergyConversionControllerTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/FuelControllerTest.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/services/PaymentServiceTest.java
  sep490-enterprise/src/test/resources/emission_sources.xlsx
Labels: technical debt, task

#327 287 dirty check directive
  sep490-frontend/src/app/app.module.ts
  sep490-frontend/src/app/components/header/header.component.html
  sep490-frontend/src/app/modules/admin/admin-routing.module.ts
  sep490-frontend/src/app/modules/admin/components/create-update-package-credit/create-update-package-credit.component.html
  sep490-frontend/src/app/modules/admin/components/credit-convert-ratio/credit-convert-ratio.component.html
  sep490-frontend/src/app/modules/admin/components/update-ratio/update-ratio.component.html
  sep490-frontend/src/app/modules/authorization/authorization-routing.module.ts
  sep490-frontend/src/app/modules/authorization/components/create-user/enterprise-user-details.component.html
  sep490-frontend/src/app/modules/authorization/components/power-bi-access-token-detail/power-bi-access-token-detail.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-details/building-details.component.html
  sep490-frontend/src/app/modules/enterprise/enterprise-routing.module.ts
  sep490-frontend/src/app/modules/shared/components/form/abstract-form-component.ts
  sep490-frontend/src/app/modules/shared/directives/unsaved-changes/global-events.service.ts
  sep490-frontend/src/app/modules/shared/directives/unsaved-changes/unsaved-changes-guard.service.ts
  sep490-frontend/src/app/modules/shared/directives/unsaved-changes/unsaved-changes.directive.ts
  sep490-frontend/src/app/modules/shared/directives/unsaved-changes/unsaved-changes.service.ts
  sep490-frontend/src/app/modules/shared/services/modal-provider.ts
  sep490-frontend/src/app/modules/shared/shared.module.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: improvement, task

#328 feat/add-profile-tenant-and-enterprise-by-Copilot AI
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/EnterpriseDetailDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/TenantDetailDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/EnterpriseMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/TenantMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/EnterpriseController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/TenantController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/EnterpriseService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/TenantService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EnterpriseServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/TenantServiceImpl.java
  sep490-frontend/src/app/app-routing.constant.ts
  sep490-frontend/src/app/components/sidebar/sidebar.component.ts
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.html
  sep490-frontend/src/app/modules/enterprise/components/enterprise-invitation/enterprise-invitation.component.html
  sep490-frontend/src/app/modules/enterprise/components/enterprise-profile/enterprise-profile.component.css
  sep490-frontend/src/app/modules/enterprise/components/enterprise-profile/enterprise-profile.component.html
  sep490-frontend/src/app/modules/enterprise/components/enterprise-profile/enterprise-profile.component.ts
  sep490-frontend/src/app/modules/enterprise/components/manage-tenant/manage-tenant.component.html
  sep490-frontend/src/app/modules/enterprise/components/tenant-profile/tenant-profile.component.css
  sep490-frontend/src/app/modules/enterprise/components/tenant-profile/tenant-profile.component.html
  sep490-frontend/src/app/modules/enterprise/components/tenant-profile/tenant-profile.component.ts
  sep490-frontend/src/app/modules/enterprise/enterprise-routing.module.ts
  sep490-frontend/src/app/modules/enterprise/enterprise.module.ts
  sep490-frontend/src/app/modules/enterprise/models/enterprise.dto.ts
  sep490-frontend/src/app/modules/enterprise/services/enterprise.service.ts
  sep490-frontend/src/app/modules/enterprise/services/tenant.service.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, task

#329 fix: missing i18n
  sep490-frontend/src/app/components/email-verify-otp/email-verify-otp.component.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
  sep490-idp/src/main/java/greenbuildings/idp/service/impl/UserServiceImpl.java
Labels: improvement

#332 refactor: improve views
  sep490-frontend/src/app/components/landing-page/landing-page.component.html
  sep490-frontend/src/app/components/sidebar/sidebar.component.ts
  sep490-frontend/src/app/modules/enterprise/components/enterprise-invitation/enterprise-invitation.component.html
  sep490-frontend/src/app/modules/enterprise/components/enterprise-invitation/enterprise-invitation.component.ts
  sep490-frontend/src/app/modules/enterprise/components/enterprise-profile/enterprise-profile.component.ts
  sep490-frontend/src/app/modules/enterprise/components/manage-tenant/manage-tenant.component.html
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: improvement, task

#333 feature: Drop items Signed-off-by: Tran Gia Bao
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/GroupItemDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/NewEmissionActivityRecordDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/NewGroupItemDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/OverviewBuildingDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/SearchGroupItemDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/BuildingEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/BuildingGroupEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/EmissionActivityRecordEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/GroupItemEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/EmissionActivityRecordMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/GroupItemMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/decorators/EmissionActivityRecordMapperDecorator.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/decorators/GroupItemMapperDecorator.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/GroupItemRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/GroupItemController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/GroupItemService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/BuildingServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/GroupItemServiceImpl.java
  sep490-enterprise/src/main/resources/db/migration/V0.0.1.44__DropItem.sql
  sep490-frontend/src/app/app-routing.constant.ts
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.ts
  sep490-frontend/src/app/modules/enterprise/components/building-management/building-management.component.html
  sep490-frontend/src/app/modules/enterprise/components/new-group-item/new-group-item.component.css
  sep490-frontend/src/app/modules/enterprise/components/new-group-item/new-group-item.component.html
  sep490-frontend/src/app/modules/enterprise/components/new-group-item/new-group-item.component.ts
  sep490-frontend/src/app/modules/enterprise/enterprise-routing.module.ts
  sep490-frontend/src/app/modules/enterprise/enterprise.module.ts
  sep490-frontend/src/app/modules/enterprise/models/enterprise.dto.ts
  sep490-frontend/src/app/modules/enterprise/services/group-item.service.ts
Labels: technical debt, task

#337 feature: Revert quantity field in record.
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/EmissionActivityRecordDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/EmissionActivityRecordEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/BuildingServiceImpl.java
  sep490-enterprise/src/main/resources/db/migration/V0.0.1.45__AddQuantityRecord.sql
  sep490-frontend/src/app/models/enterprise.ts
  sep490-frontend/src/app/modules/enterprise/components/emission-activity-detail/emission-activity-detail.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/new-activity-record-dialog/new-activity-record-dialog.component.html
  sep490-frontend/src/app/modules/enterprise/dialog/new-activity-record-dialog/new-activity-record-dialog.component.ts
Labels: user story, improvement, task

#338 feature: Display common activity report
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/OverviewBuildingDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/EmissionActivityRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/BuildingServiceImpl.java
  sep490-frontend/src/app/models/enterprise.ts
  sep490-frontend/src/app/modules/enterprise/components/building-management/building-management.component.html
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, improvement, task

#341 Refactor
  sep490-enterprise/src/main/java/greenbuildings/enterprise/securities/ResourceServerConfig.java
  sep490-frontend/package.json
  sep490-frontend/src/app/model/api-key-response.ts
  sep490-frontend/src/app/model/building-permission-dto.ts
  sep490-frontend/src/app/model/enterprise-user-details-dto.ts
  sep490-frontend/src/app/model/enterprise-user-dto.ts
  sep490-frontend/src/app/model/new-enterprise-dto.ts
  sep490-frontend/src/app/model/power-bi-authority-dto.ts
  sep490-frontend/src/app/model/regenerate-token-body.ts
  sep490-frontend/src/app/model/search-criteria-dto-user-criteria-dto.ts
  sep490-frontend/src/app/model/search-result-dto-enterprise-user-dto.ts
  sep490-frontend/src/app/model/search-result-dto-user-by-building-dto.ts
  sep490-frontend/src/app/model/user-by-building-dto.ts
  sep490-frontend/src/app/model/user-configs.ts
  sep490-frontend/src/app/model/user-criteria-dto.ts
  sep490-frontend/src/app/model/validate-otp-request.ts
  sep490-frontend/src/app/modules/admin/admin.module.ts
  sep490-frontend/src/app/modules/admin/components/user-details/user-details.component.css
  sep490-frontend/src/app/modules/admin/components/user-details/user-details.component.html
  sep490-frontend/src/app/modules/admin/components/user-details/user-details.component.ts
  sep490-frontend/src/app/modules/authorization/authorization-routing.module.ts
  sep490-frontend/src/app/modules/authorization/authorization.module.ts
  sep490-frontend/src/app/modules/authorization/components/users-management/users.component.css
  sep490-frontend/src/app/modules/authorization/components/users-management/users.component.html
  sep490-frontend/src/app/modules/authorization/components/users-management/users.component.ts
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.html
  sep490-frontend/src/app/modules/enterprise/components/manage-tenant/manage-tenant.component.html
  sep490-frontend/src/app/modules/enterprise/components/tenant-profile/tenant-profile.component.html
  sep490-frontend/src/app/services/enterprise-user.service.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
  sep490-idp/build.gradle
  sep490-idp/src/main/java/greenbuildings/idp/configs/AuthorizationServerConfig.java
  sep490-idp/src/main/java/greenbuildings/idp/controller/PasskeyController.java
Labels: technical debt, improvement

#345 feature: Sort invitation by date and status by default. Add validatio…
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/BuildingGroupRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/InvitationRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/InvitationController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/BuildingGroupServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/InvitationServiceImpl.java
  sep490-frontend/src/app/modules/enterprise/components/enterprise-invitation/enterprise-invitation.component.ts
  sep490-frontend/src/app/modules/enterprise/components/sent-invitation/sent-invitation.component.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, improvement, task

#346 Bugfix dev qc bugs
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/BuildingEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/BuildingRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/BuildingGroupController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/EmissionActivityRecordController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/BuildingGroupService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/EmissionActivityRecordService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/MinioService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/BuildingGroupServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/EmissionActivityRecordServiceImpl.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/BuildingGroupControllerTest.java
  sep490-frontend/src/app/modules/enterprise/components/buildings/buildings.component.html
  sep490-frontend/src/app/modules/enterprise/components/emission-activity-detail/emission-activity-detail.component.scss
  sep490-frontend/src/app/modules/enterprise/components/emission-activity-detail/emission-activity-detail.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/new-activity-record-dialog/new-activity-record-dialog.component.ts
  sep490-frontend/src/app/services/emission-activity-record.service.ts
Labels: bug, improvement, task

#347 feature: Add title for list, display pending invitation
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/InvitationRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/InvitationController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/InvitationService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/InvitationServiceImpl.java
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-group-detail/building-group-detail.component.ts
  sep490-frontend/src/app/modules/enterprise/components/building-management/building-management.component.html
  sep490-frontend/src/app/services/invitation.service.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, improvement, task

#349 feature: Linked Tenant Component
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/SearchTenantCriteria.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/TenantTableView.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/TenantMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/TenantRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/TenantController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/TenantService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/TenantServiceImpl.java
  sep490-enterprise/src/test/java/greenbuildings/enterprise/rest/TenantControllerTest.java
  sep490-frontend/src/app/app-routing.constant.ts
  sep490-frontend/src/app/components/sidebar/sidebar.component.ts
  sep490-frontend/src/app/modules/admin/components/emission-factor/emission-factor.component.html
  sep490-frontend/src/app/modules/admin/components/emission-source/emission-source.component.html
  sep490-frontend/src/app/modules/admin/components/fuel-conversion/fuel-conversion.component.html
  sep490-frontend/src/app/modules/enterprise/components/linked-tenant/linked-tenant.component.css
  sep490-frontend/src/app/modules/enterprise/components/linked-tenant/linked-tenant.component.html
  sep490-frontend/src/app/modules/enterprise/components/linked-tenant/linked-tenant.component.ts
  sep490-frontend/src/app/modules/enterprise/enterprise-routing.module.ts
  sep490-frontend/src/app/modules/enterprise/enterprise.module.ts
  sep490-frontend/src/app/services/tenant.service.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
Labels: user story, improvement, task

#348 Dev qc bugs
  sep490-commons-springfw-impl/src/main/java/commons/springfw/impl/securities/JwtAuthenticationConverter.java
  sep490-commons-springfw-impl/src/main/java/commons/springfw/impl/securities/UserContextData.java
  sep490-commons-springfw-impl/src/main/java/commons/springfw/impl/utils/SecurityUtils.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/adapters/payos/payos/PayOSAdapterImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/consumers/EnterpriseEventConsumer.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/InvitationController.java
  sep490-frontend/src/app/modules/enterprise/components/create-enterprise/create-enterprise.component.html
  sep490-frontend/src/app/modules/enterprise/components/create-enterprise/create-enterprise.component.ts
  sep490-frontend/src/app/modules/enterprise/components/new-tenant/new-tenant.component.html
  sep490-frontend/src/app/modules/enterprise/components/plan/plan.component.html
  sep490-frontend/src/app/modules/enterprise/components/plan/plan.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/credit-package-guide-dialog/credit-package-guide-dialog.component.html
  sep490-frontend/src/app/modules/shared/services/toast-provider.ts
  sep490-frontend/src/assets/i18n/en.json
  sep490-frontend/src/assets/i18n/vi.json
  sep490-frontend/src/assets/i18n/zh.json
  sep490-idp/src/main/java/greenbuildings/idp/dto/UserByBuildingDTO.java
  sep490-idp/src/main/java/greenbuildings/idp/entity/UserEntity.java
  sep490-idp/src/main/java/greenbuildings/idp/entity/UserPermissionEntity.java
  sep490-idp/src/main/java/greenbuildings/idp/mapper/EnterpriseUserMapper.java
  sep490-idp/src/main/java/greenbuildings/idp/mapper/decoratos/EnterpriseUserMapperDecorator.java
  sep490-idp/src/main/java/greenbuildings/idp/repository/BuildingPermissionRepository.java
  sep490-idp/src/main/java/greenbuildings/idp/repository/UserRepository.java
  sep490-idp/src/main/java/greenbuildings/idp/rest/EnterpriseUserRestController.java
  sep490-idp/src/main/java/greenbuildings/idp/rest/UserResource.java
  sep490-idp/src/main/java/greenbuildings/idp/security/MvcUserContextData.java
  sep490-idp/src/main/java/greenbuildings/idp/service/UserService.java
  sep490-idp/src/main/java/greenbuildings/idp/service/impl/LoginService.java
  sep490-idp/src/main/java/greenbuildings/idp/service/impl/UserDetailsServiceImpl.java
  sep490-idp/src/main/java/greenbuildings/idp/service/impl/UserInfoService.java
  sep490-idp/src/main/java/greenbuildings/idp/service/impl/UserServiceImpl.java
  sep490-idp/src/main/java/greenbuildings/idp/utils/IdpSecurityUtils.java
  sep490-idp/src/main/java/greenbuildings/idp/validators/UserValidator.java
  sep490-idp/src/main/resources/db/migration/V0.0.1.17__CorrectUserPermissionOnBuildingAndTenant.sql
  sep490-infrastructure/keycloak-testcontainer-provider/build.sh
  sep490-infrastructure/keycloak-testcontainer-provider/src/main/java/keycloak/provider/Sep490IdentityProviderTokenMapper.java
Labels: technical debt, user story, improvement, task

#357 Dev qc bugs
  sep490-commons-api/src/main/java/greenbuildings/commons/api/dto/SearchCriteriaDTO.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/dtos/InvitationSearchCriteria.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/BuildingEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/entities/BuildingGroupEntity.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/mappers/BuildingGroupMapper.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/BuildingGroupRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/InvitationRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/repositories/TenantRepository.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/BuildingController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/rest/InvitationController.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/BuildingGroupService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/InvitationService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/TenantService.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/BuildingGroupServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/InvitationServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/services/impl/TenantServiceImpl.java
  sep490-enterprise/src/main/java/greenbuildings/enterprise/views/buildings/details/TenantView.java
  sep490-frontend/src/app/model/building-group-view.ts
  sep490-frontend/src/app/model/building-view.ts
  sep490-frontend/src/app/model/search-criteria-dto-search-tenant-criteria.ts
  sep490-frontend/src/app/model/search-result-dto-tenant-table-view.ts
  sep490-frontend/src/app/model/search-result-dto-tenant-view.ts
  sep490-frontend/src/app/model/search-tenant-criteria.ts
  sep490-frontend/src/app/model/tenant-table-view.ts
  sep490-frontend/src/app/model/tenant-view.ts
  sep490-frontend/src/app/models/tenant.ts
  sep490-frontend/src/app/modules/enterprise/components/building-details/building-details.component.html
  sep490-frontend/src/app/modules/enterprise/components/building-details/building-details.component.ts
  sep490-frontend/src/app/modules/enterprise/components/emission-activity-detail/emission-activity-detail.component.ts
  sep490-frontend/src/app/modules/enterprise/components/sent-invitation/sent-invitation.component.ts
  sep490-frontend/src/app/modules/enterprise/components/tenant-profile/tenant-profile.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/activity-type-dialog/activity-type-dialog.component.ts
  sep490-frontend/src/app/modules/enterprise/dialog/new-activity-dialog/new-activity-dialog.component.ts
  sep490-frontend/src/app/services/activity-type.service.ts
  sep490-frontend/src/app/services/application.service.ts
  sep490-frontend/src/app/services/building.service.ts
Labels: bug, improvement, task
